language: r
sudo: required

r_build_args: --no-build-vignettes --no-manual --no-resave-data
r_check_args: --run-donttest --no-build-vignettes --no-manual

warnings_are_errors: true

r_binary_packages:
 - numDeriv
 - lava
 - testthat

r_github_packages:
 - jimhester/covr
 - mangothecat/visualTest

after_success:
  - Rscript -e 'library("covr");codecov(type="all")'
