language: r
sudo: required

r_check_args: --as-cran --run-donttest

warnings_are_errors: true

r_binary_packages:
 - numDeriv
 - lava
 - testthat

r_github_packages:
 - jimhester/covr
 - mangothecat/visualTest

after_success:
  - Rscript -e 'covr::codecov()'
